"""
Exp036 — AfriVoices Manifest Builder Skeleton

Purpose:
Build a unified AfriVoices dataset manifest from multiple Hugging Face sources.

Status:
Skeleton only. Full Anv-ke ingestion is pending gated dataset access approval.
"""

from pathlib import Path
from dataclasses import dataclass
from typing import Dict, List


OUTPUT_DIR = Path("data/afrivoices/manifests")
REPORT_DIR = Path("reports/dataset_analysis")


@dataclass
class DatasetSource:
    language: str
    iso_code: str
    repo_id: str
    status: str
    notes: str


SOURCES: List[DatasetSource] = [
    DatasetSource(
        language="Swahili",
        iso_code="swa",
        repo_id="DigitalUmuganda/Afrivoice_Swahili",
        status="accessible_legacy_script",
        notes="Accessible but uses legacy Hugging Face dataset script format.",
    ),
    DatasetSource(
        language="Somali Mogadishu",
        iso_code="som",
        repo_id="DigitalUmuganda/Afrivoice",
        status="accessible_file_repo",
        notes="Accessible repository; needs file-based manifest extraction.",
    ),
    DatasetSource(
        language="Kikuyu",
        iso_code="kik",
        repo_id="Anv-ke/kikuyu",
        status="gated_pending",
        notes="Repository listing visible; file download blocked until access approval.",
    ),
    DatasetSource(
        language="Luo",
        iso_code="luo",
        repo_id="Anv-ke/Dholuo",
        status="gated_pending",
        notes="Pending access approval.",
    ),
    DatasetSource(
        language="Kalenjin",
        iso_code="kln",
        repo_id="Anv-ke/Kalenjin",
        status="gated_pending",
        notes="Pending access approval.",
    ),
    DatasetSource(
        language="Maasai",
        iso_code="mas",
        repo_id="Anv-ke/Maasai",
        status="gated_pending",
        notes="Pending access approval.",
    ),
    DatasetSource(
        language="Somali Maxatire",
        iso_code="som",
        repo_id="Anv-ke/Somali",
        status="gated_pending",
        notes="Pending access approval.",
    ),
]


def ensure_dirs() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)


def write_access_report() -> None:
    report_path = REPORT_DIR / "afrivoices_access_status.md"

    lines = [
        "# AfriVoices Data Access Status",
        "",
        "Generated by `scripts/build_afrivoices_manifest.py`.",
        "",
        "| Language | ISO | Repository | Status | Notes |",
        "|----------|-----|------------|--------|-------|",
    ]

    for source in SOURCES:
        lines.append(
            f"| {source.language} | {source.iso_code} | `{source.repo_id}` | "
            f"{source.status} | {source.notes} |"
        )

    lines.extend(
        [
            "",
            "## Current Conclusion",
            "",
            "Full six-language AfriVoices training is blocked until Anv-ke gated dataset access is approved.",
            "",
            "The manifest builder will be expanded once file download access is available.",
            "",
        ]
    )

    report_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote access report: {report_path}")


def write_manifest_schema() -> None:
    schema_path = OUTPUT_DIR / "manifest_schema.md"

    schema = """# AfriVoices Unified Manifest Schema

Each final manifest row should contain:

| Column | Description |
|--------|-------------|
| id | Unique utterance ID |
| language | ISO 639-3 language code |
| language_name | Human-readable language name |
| source_repo | Hugging Face source repository |
| split | train / dev / test |
| speech_type | scripted / unscripted / unknown |
| audio_path | Local audio path or resolved HF file reference |
| transcription | Ground-truth transcript when available |
| duration_seconds | Audio duration in seconds |
| sample_rate | Audio sample rate |
| speaker_id | Speaker identifier if available |
| dialect | Dialect or region if available |
| metadata | Optional raw metadata JSON |

Target output files:

- data/afrivoices/manifests/manifest_train.parquet
- data/afrivoices/manifests/manifest_dev.parquet
- data/afrivoices/manifests/manifest_test.parquet
"""

    schema_path.write_text(schema, encoding="utf-8")
    print(f"Wrote manifest schema: {schema_path}")


def main() -> None:
    ensure_dirs()
    write_access_report()
    write_manifest_schema()
    print("Exp036 manifest builder skeleton complete.")


if __name__ == "__main__":
    main()
